services:
  wagtail:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: cli
    image: ${COMPOSE_PROJECT_NAME_SAFE}_wagtail
    build:
      dockerfile: services/wagtail/Dockerfile
      args:
        - CLI_IMAGE=${CLI_IMAGE}
    command: ["/start"]
    volumes:
      - ${PROJECT_ROOT}/../server:/server:ro
      - ${PROJECT_ROOT}/../data:/data:rw
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-default}
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-user}
      - POSTGRES_HOST=${POSTGRES_HOST:-db}
      - PGSQL_PORT_MAPPING=${PGSQL_PORT_MAPPING:-5432}
      - WAGTAILADMIN_BASE_URL=${VIRTUAL_HOST}:${VIRTUAL_HOST_PORT:-8000}
    labels:
      - io.docksal.virtual-host=${VIRTUAL_HOST},*.${VIRTUAL_HOST},${VIRTUAL_HOST}.*
      - io.docksal.virtual-port=${VIRTUAL_HOST_PORT:-8000}
      - io.docksal.cert-name=${VIRTUAL_HOST_CERT_NAME:-none}
      - io.docksal.project-root=${PROJECT_ROOT}
      - io.docksal.permanent=${SANDBOX_PERMANENT:-false}
  cli:
    image: ${COMPOSE_PROJECT_NAME_SAFE}_cli
    build:
      dockerfile: services/cli/Dockerfile
      args:
        - CLI_IMAGE=${CLI_IMAGE}
    volumes:
      - ${PROJECT_ROOT}/../server:/server:ro
      - ${PROJECT_ROOT}/../data:/data:rw
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-default}
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-user}
      - POSTGRES_HOST=${POSTGRES_HOST:-db}
      - PGSQL_PORT_MAPPING=${PGSQL_PORT_MAPPING:-5432}
      - WAGTAILADMIN_BASE_URL=${VIRTUAL_HOST}:${VIRTUAL_HOST_PORT:-8000}
    labels:
      - io.docksal.virtual-host=cli.${VIRTUAL_HOST}
  db:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: pgsql
    volumes:
      - ${PROJECT_ROOT}/../server:/var/server:ro
      - ${PROJECT_ROOT}/../data:/var/data:rw
  mail:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: mail
    labels:
      - io.docksal.virtual-host=webmail.${VIRTUAL_HOST}
